package types

type Type int

const (
	Enum Type = iota
	Sint8
	Uint8
	Sint16
	Uint16
	Sint32
	Uint32
	String
	Float32
	Float64
	Uint8z
	Uint16z
	Uint32z
	Byte
	Sint64
	Uint64
	Uint64z
	Bool
	File
	MesgNum
	Checksum
	FileFlags
	MesgCount
	DateTime
	LocalDateTime
	MessageIndex
	DeviceIndex
	Gender
	Language
	LanguageBits0
	LanguageBits1
	LanguageBits2
	LanguageBits3
	LanguageBits4
	TimeZone
	DisplayMeasure
	DisplayHeart
	DisplayPower
	DisplayPosition
	Switch
	Sport
	SportBits0
	SportBits1
	SportBits2
	SportBits3
	SportBits4
	SportBits5
	SportBits6
	SubSport
	SportEvent
	Activity
	Intensity
	SessionTrigger
	AutolapTrigger
	LapTrigger
	TimeMode
	BacklightMode
	DateMode
	BacklightTimeout
	Event
	EventType
	TimerTrigger
	FitnessEquipmentState
	Tone
	Autoscroll
	ActivityClass
	HrZoneCalc
	PwrZoneCalc
	WktStepDuration
	WktStepTarget
	Goal
	GoalRecurrence
	GoalSource
	Schedule
	CoursePoint
	Manufacturer
	GarminProduct
	AntplusDeviceType
	AntNetwork
	WorkoutCapabilities
	BatteryStatus
	HrType
	CourseCapabilities
	Weight
	WorkoutHr
	WorkoutPower
	BpStatus
	UserLocalId
	SwimStroke
	ActivityType
	ActivitySubtype
	ActivityLevel
	Side
	LeftRightBalance
	LeftRightBalance100
	LengthType
	DayOfWeek
	ConnectivityCapabilities
	WeatherReport
	WeatherStatus
	WeatherSeverity
	WeatherSevereType
	TimeIntoDay
	LocaltimeIntoDay
	StrokeType
	BodyLocation
	SegmentLapStatus
	SegmentLeaderboardType
	SegmentDeleteStatus
	SegmentSelectionType
	SourceType
	LocalDeviceType
	DisplayOrientation
	WorkoutEquipment
	WatchfaceMode
	DigitalWatchfaceLayout
	AnalogWatchfaceLayout
	RiderPositionType
	PowerPhaseType
	CameraEventType
	SensorType
	BikeLightNetworkConfigType
	CommTimeoutType
	CameraOrientationType
	AttitudeStage
	AttitudeValidity
	AutoSyncFrequency
	ExdLayout
	ExdDisplayType
	ExdDataUnits
	ExdQualifiers
	ExdDescriptors
	AutoActivityDetect
	SupportedExdScreenLayouts
	FitBaseType
	TurnType
	BikeLightBeamAngleMode
	FitBaseUnit
	SetType
	ExerciseCategory
	BenchPressExerciseName
	CalfRaiseExerciseName
	CardioExerciseName
	CarryExerciseName
	ChopExerciseName
	CoreExerciseName
	CrunchExerciseName
	CurlExerciseName
	DeadliftExerciseName
	FlyeExerciseName
	HipRaiseExerciseName
	HipStabilityExerciseName
	HipSwingExerciseName
	HyperextensionExerciseName
	LateralRaiseExerciseName
	LegCurlExerciseName
	LegRaiseExerciseName
	LungeExerciseName
	OlympicLiftExerciseName
	PlankExerciseName
	PlyoExerciseName
	PullUpExerciseName
	PushUpExerciseName
	RowExerciseName
	ShoulderPressExerciseName
	ShoulderStabilityExerciseName
	ShrugExerciseName
	SitUpExerciseName
	SquatExerciseName
	TotalBodyExerciseName
	TricepsExtensionExerciseName
	WarmUpExerciseName
	RunExerciseName
	WaterType
	TissueModelType
	DiveGasStatus
	DiveAlarmType
	DiveBacklightMode
	FaveroProduct
	ClimbProEvent
	TapSensitivity
	RadarThreatLevelType
	NumTypes
)
